version: 2.1

jobs:
  build-and-test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run:
          name: Set up Python venv
          command: |
            python3 -m venv venv
            source venv/bin/activate
      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            pip install --no-cache-dir -r requirements.txt
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - setup_remote_docker:
          version: 20.10.7  # Version de Docker à utiliser
      - run:
          name: Build Docker image
          command: |
            docker build -t ffnn:latest .
      - run:
          name: Run Docker container
          command: |
            docker run -p 8080:80 ffnn:latest
      - run:
          name: Run unit tests
          command: |
            python -m unittest test_unnitest.py

workflows:
  build-and-test:
    jobs:
      - build-and-test
