version: 2.1

jobs:
  build-and-test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            python -m unittest test_unnitest.py


workflows:
  build-and-test:
    jobs:
      - build-and-test
