version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    environment:
      DOCKER_HOST: tcp://localhost:2375
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo service docker start
      - run:
          command: |
            pip install --upgrade pip  
            pip install -r requirements.txt 
            python test_unnitest.py
      - run:
          name: Build Docker image
          command: |
            docker build -t ffnn:latest .
