version: 2.1

jobs:
  build-and-test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.8/site-packages
      - run:
          name: Run unit tests
          command: |
            python -m unittest test_unnitest.py

workflows:
  build-and-test:
    jobs:
      - build-and-test
