version: 2.1

executors:
  docker-executor:
    docker:
      - image: "circleci/python:3.8"
    environment:
      DOCKER_HOST: tcp://localhost:2375

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Version de Docker à utiliser
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Build Docker image
          command: |
            docker build -t ffnn:latest .
      - run:
          name: Run unit tests
          command: |
            python -m unittest test_unnitest.py

workflows:
  build-and-test:
    jobs:
      - build
